package net.pastek.chemicalscience.registers.fluids;

import net.neoforged.bus.api.IEventBus;
import electrodynamics.registers.ElectrodynamicsItems;
import net.minecraft.core.registries.Registries;
import net.minecraft.world.level.material.Fluid;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.pastek.chemicalscience.ChemicalScience;
import voltaic.common.fluid.FluidNonPlaceable;
import voltaic.common.fluid.SimpleWaterBasedFluidType;
import voltaic.prefab.utilities.math.Color;


public class CSFluids {
    public static final DeferredRegister<Fluid> FLUIDS = DeferredRegister.create(Registries.FLUID, ChemicalScience.MOD_ID);

    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_POTASSIUMCHLORIDE = FLUIDS.register("potassiumchloride", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "potassiumchloride", "colorlessfluid", new Color(240, 240, 255, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_SILICIUMTETRACHLORIDE = FLUIDS.register("siliciumtetrachloride", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "siliciumtetrachloride", "siliciumtetrachloride", new Color(180, 190, 180, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_MAGNESIUMSULFATE = FLUIDS.register("sulfatemagnesium", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "sulfatemagnesium", "sulfatemagnesium", new Color(255, 255, 255, 180))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_PHOSPHORICACID = FLUIDS.register("phosphoricacid", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "phosphoricacid", "phosphoricacid", new Color(255, 255, 200, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_CALCIUMHYDROXIDE = FLUIDS.register("calciumhydroxide", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "calciumhydroxide", "colorlessfluid", new Color(255, 255, 255, 220))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_SODIUMHYDROXIDE = FLUIDS.register("sodiumhydroxide", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "sodiumhydroxide", "colorlessfluid", new Color(255, 255, 255, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_ARSENICTRICHLORIDE = FLUIDS.register("arsenictrichloride", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "arsenictrichloride", "arsenictrichloride", new Color(255, 255, 0, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_BROMINE = FLUIDS.register("bromine", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "bromine", "bromine", new Color(70, 20, 0, 220))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_CHLORINE = FLUIDS.register("chlorine", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "chlorine", "chlorine", new Color(150, 220, 0, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_METHANOL = FLUIDS.register("methanol", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "methanol", "colorlessfluid", new Color(255, 255, 255, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_COPPERNITRATE = FLUIDS.register("coppernitrate", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "coppernitrate", "coppernitrate", new Color(0, 50, 255, 220))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_CARBONMONOXIDE = FLUIDS.register("carbonmonoxide", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "carbonmonoxide", "colorlessfluid", new Color(0, 0, 0, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_ACETICACID = FLUIDS.register("aceticacid", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "aceticacid", "colorlessfluid", new Color(255, 255, 255, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_BENZENE = FLUIDS.register("benzene", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "benzene", "benzene", new Color(255, 255, 255, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_TOLUENE = FLUIDS.register("toluene", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "toluene", "colorlessfluid", new Color(255, 255, 255, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_IRONNITRATE = FLUIDS.register("ironnitrate", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "ironnitrate", "ironnitrate", new Color(255, 200, 255, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_DIESEL = FLUIDS.register("diesel", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "diesel", "diesel", new Color(150, 150, 0, 220))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_MALEICACID = FLUIDS.register("maleicacid", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "maleicacid", "colorlessfluid", new Color(255, 255, 255, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_ESCHERICHIACOLI = FLUIDS.register("escherichia_coli", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "escherichia_coli", "escherichia_coli", new Color(255, 183, 198, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_TRIETHYLPHOSPHATE = FLUIDS.register("triethylphosphate", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "triethylphosphate", "colorlessfluid", new Color(255, 255, 255, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_BROMOACETICACID = FLUIDS.register("bromoaceticacid", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "bromoaceticacid", "colorlessfluid", new Color(255, 255, 220, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_ETHYLBROMOACETATE = FLUIDS.register("ethylbromoacetate", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "ethylbromoacetate", "colorlessfluid", new Color(255, 255, 200, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_BENZONITRILE = FLUIDS.register("benzonitrile", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "benzonitrile", "colorlessfluid", new Color(255, 255, 255, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_SUCCINICACID = FLUIDS.register("succinicacid", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "succinicacid", "colorlessfluid", new Color(255, 255, 255, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_AMMONIUMSUCCINATE = FLUIDS.register("ammoniumsuccinate", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "ammoniumsuccinate", "colorlessfluid", new Color(255, 255, 255, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_SODIUMPERCHLORATE = FLUIDS.register("sodiumperchlorate", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "sodiumperchlorate", "colorlessfluid", new Color(255, 255, 255, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_PERCHLORICACID = FLUIDS.register("perchloricacid", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "perchloricacid", "colorlessfluid", new Color(255, 255, 255, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_TETRACHLOROMETHANE = FLUIDS.register("tetrachloromethane", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "tetrachloromethane", "colorlessfluid", new Color(255, 255, 255, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_CHLOROBENZENE = FLUIDS.register("chlorobenzene", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "chlorobenzene", "colorlessfluid", new Color(255, 255, 255, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_BUTANE = FLUIDS.register("butane", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "butane", "colorlessfluid", new Color(0, 0, 0, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_THIOPHENE = FLUIDS.register("thiophene", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "thiophene", "colorlessfluid", new Color(255, 255, 240, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_PALLADIUMPHOSPHATE = FLUIDS.register("palladiumphosphate", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "palladiumphosphate", "palladiumphosphate", new Color(90, 0, 120, 180))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_ROYALMINERALPLATINUM = FLUIDS.register("fluidroyalmineralplatinum", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "fluidroyalmineralplatinum", "fluidroyalmineralplatinum", new Color(160, 80, 20, 220))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_ROYALMINERALPALLADIUM = FLUIDS.register("fluidroyalmineralpalladium", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "fluidroyalmineralpalladium", "fluidroyalmineralpalladium", new Color(100, 20, 0, 220))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_HYDROBROMIC_ACID = FLUIDS.register("hydrobromicacid", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "hydrobromicacid", "colorlessfluid", new Color(180, 180, 120, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_BROMOMETHANE = FLUIDS.register("bromomethane", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "bromomethane", "colorlessfluid", new Color(255, 255, 255, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_MALONICACID = FLUIDS.register("malonicacid", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "malonicacid", "colorlessfluid", new Color(255, 255, 255, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_CHLOROACETICACID = FLUIDS.register("chloroaceticacid", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "chloroaceticacid", "colorlessfluid", new Color(255, 255, 255, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_CRUDEOIL = FLUIDS.register("crudeoil", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "crudeoil", "oilfluid", new Color(0, 0, 0, 240))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_IMPUREPETROLEUMGAS = FLUIDS.register("impurepetroleumgas", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "impurepetroleumgas", "oilfluid", new Color(180, 140, 0, 200))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_IMPURENAPHTA = FLUIDS.register("impurenaphta", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "impurenaphta", "oilfluid", new Color(150, 150, 220, 200))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_IMPUREDIESEL = FLUIDS.register("impurediesel", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "impurediesel", "oilfluid", new Color(180, 220, 60, 200))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_IMPUREHEAVYOIL = FLUIDS.register("impureheavyoil", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "impureheavyoil", "oilfluid", new Color(0, 0, 0, 200))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_PROPANE = FLUIDS.register("propane", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "propane", "colorlessfluid", new Color(120, 40, 0, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_METHANE = FLUIDS.register("methane", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "methane", "colorlessfluid", new Color(120, 40, 0, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_NAPHTA = FLUIDS.register("naphta", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "naphta", "oilfluid", new Color(120, 120, 180, 120))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_HEAVYOIL = FLUIDS.register("heavyoil", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "heavyoil", "oilfluid", new Color(0, 0, 0, 60))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_FUEL = FLUIDS.register("fuel", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "fuel", "fuel", new Color(190, 170, 100, 220))));
    public static DeferredHolder<Fluid, FluidNonPlaceable> FLUID_HYDROGENSULFIDE = FLUIDS.register("hydrogensulfide", () -> new FluidNonPlaceable(ElectrodynamicsItems.ITEM_CANISTERREINFORCED, new SimpleWaterBasedFluidType(ChemicalScience.MOD_ID, "hydrogensulfide", "hydrogensulfide", new Color(230, 255, 0, 180))));





    public static void register(IEventBus eventBus) {
        FLUIDS.register(eventBus);
    }
}
