## Loader Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.3.1
loader_version_range=[43,)
mixin_version=0.8.5
jei_version=15.20.0.112

mod_id=chemicalscience
mod_version=3.0.1
mod_name=Chemical Science
mod_description=An addon for Electrodynamics expending chemistry.



