modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory
license="ARR"
[[mods]] #mandatory

modId="chemicalscience" #mandatory
version="1.20.1-3.0.4" #mandatory
displayName="Chemical Science" #mandatory
authors="Roi Pasteque" #optional
description='''${mod_description}'''
logoFile="chemicalscience.png"
displayURL = "https://github.com/roipasteque/ChemicalScience"

[[dependencies.chemicalscience]]
modId="minecraft"
type="required"
versionRange="[1.20.1, 1.20.2)"
ordering="NONE"
side="BOTH"
mandatory=true

[[dependencies.chemicalscience]]
modId="electrodynamics"
type="required"
versionRange="[0.9,)"
ordering="NONE"
side="BOTH"
mandatory=true

[[dependencies.chemicalscience]]
modId="voltaic"
type="required"
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"
mandatory=true
